services:
  - type: web
    name: talent-tution-classes
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: MONGODB_URI
        value: "mongodb+srv://veersukhadiya97_db_user:YS3Bnc5X0ygXEYkt@talent-student-tracker.us1eitw.mongodb.net/?appName=talent-student-tracker"
